### ISSUE TITLE
Keeps reverting back to OpenWeatherMap weather provider. 

### ISSUE THREAD

**Issue by snaggen** [kylewlacy/futura-weather-redux#13] opened 2014-02-02 17:38 UTC
Using the latest code, I select Yahoo Weather or yr.no as the weather provider (since OpenWeatherMap have a bug in my area causing the weather to be a bit off). However, after a while it seems that the weather provider is reverted back to OpenWeatherMap. I don't know why and I haven't investigated it yet. 
I wonder if it might be that the javascript is killed and restarted by the phone OS (I read somewhere that this might happen), and it fails to read in the preferences again. The language selection seems to still be ok, but it might be that the date layer just isn't updated.

**Comment by snaggen** [comment] 2014-02-02 18:07
I have taken a look at the code, and I can't see any obvious faults around the settings... However, I read about some problems with the persistent storage with some betas. I wonder if it might be some similar thing that happens to me. I will do a factory reset when I upgrade to the stable 2.0 and see if the issue goes away. For now I re-installed the app, since that will re-initialize the persistent storage. 
I suspect that this isn't a problem within this watchface, but it might be a good idea to keep this issue open so it isn't forgotten.

**Comment by kylewlacy** [comment] 2014-02-02 19:20
I have noticed this problem as well, but I'm pretty sure it's independent from the persistent storage errors (which makes it so no data can be saved or loaded; something that seems to be more likely the more frequently you reinstall an app).

I'll try to debug the issue later today.

**Comment by kylewlacy** [comment] 2014-02-02 19:31
So the problem was with the code for saving the preferences; the provider was being saved with a call to `persist_write_bool` (where it should have been `persist_write_int`). Fixed in commit 9bf4991ff39febf50ab34adefe6aac4d97be6e0a.

**Comment by snaggen** [comment] 2014-02-02 20:35
Ahh.. nice spotted! I was just running a build with quite a lot of debug, that just put me to investigate this part of the code... but you beat me to it :)

**Comment by snaggen** [comment] 2014-02-03 12:17
You need to reopen this issue, there are more bugs causing reverts. Even with this fix when you run another app and then go back to the watchface it will revert back to the default settings. 
After I added a lot of debug I see that what happens is that the preferences_send message will always fail with : "Sending message failed (reason 2)". This is the APP_MSG_SEND_TIMEOUT error.  
I thought this was due to the message being sent before the javascript was ready, so i send a "ready" message from the javascript to the watch app in the js ready event. Then in the callback I sent the preferences, that way the javascript app will always be up and running. However, this didn't help anything, still fails. I then changed to send the request weather update message at that point but then that failed, even though it works fine at a later point. This is really weird... 
It seems that is might be this issue we are seeing: http://forums.getpebble.com/discussion/10576/appmessage-and-android

**Comment by kylewlacy** [comment] 2014-02-03 14:13
I can't reproduce this on iOS, so I'm assuming this is an Android-specific issue. I'm also assuming that this is just a failure on Pebble's part (since it work fine on iOS).

However, the watchface only sends the preferences to the JS app when it first loads, which means that, if the JS is killed, then the preference page will always revert to defaults. I'd like to redo that logic, so I'll leave this issue open to see if that fixes your problem (in the case it isn't a failure on Pebble's part).

**Comment by snaggen** [comment] 2014-02-03 14:34
I created a branch called delayed_send, which adds this commit (se below)  that will cause settings to be resent and to be send again with a delay if the first sending fails. It is really ugly, but it seems to fix the issue.
https://github.com/snaggen/futura-weather-redux/commit/c9d1d4858132e9d7dca864621623f962ae377ca9

**Comment by snaggen** [comment] 2014-02-03 15:24
If we look at the more general problem as you mention in your comment, the preferences are something that always should be in sync between the app and the js. I guess the app_sync_ mechanism is better suited for that instead of sending messages back and forward. 
Also from a design perspective, the preferences should only have default values in one place, where they are read from the persistent storage. All other preference values should come from that, and using app_sync for preferences might make this easier too. 

When I implemented the Yahoo Weather provider I looked at the simplicity with day watchface, and that used this mechanism. You can look at the app_sync_init at https://github.com/snaggen/simplicity-with-day/blob/master/src/simplicity.c

Implementing preferences with the sync mechanism will probably solve this issue.

**Comment by snaggen** [comment] 2014-02-03 20:27
Ok, I threw together some test code using the app_sync for preferences. It doesn't really work, and I still get some sync errors... not sure if this really solves the sending error issue. 
https://github.com/snaggen/futura-weather-redux/tree/sync_preferences

**Comment by kylewlacy** [comment] 2014-02-03 21:52
I think a better solution would be to just use the PebbleKit-JS Storage API to save the preferences (the PebbleKit-JS Storage API is based on the [W3C WebStorage recommendation](http://www.w3.org/TR/webstorage/)). This isn't the best solution, but I think it's the most straightforward solution to this problem (especially since Pebble's Bluetooth communication has historically been pretty buggy).

**Comment by snaggen** [comment] 2014-02-04 05:53
Yes that sounds like the simplest solution to these problems, also a very clean solution since most preferences are only used by the js-code.

**Comment by snaggen** [comment] 2014-02-05 22:14
This issue seems to be fixed with the js storage solution.

**Closed as completed** 2014-02-05 22:14 UTC
